Unquote boolean values in the templated HCL files.
ansible-community/ansible-vault pull request #341
Opened 2024-05-15 00:45 UTC by macourteau

The `tls_disable` value in particular was causing the UI to show that TLS was disabled despite being actually enabled. That's likely a bug in the Vault UI code, but there's also no reason to quote the boolean values in the rendered HCL file.

2025-11-27 13:10 UTC, lakrass requested changes
I see your point here! 

Please use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and rebase your branch. 

Then I'll approve the PR!

2026-05-19 15:52 UTC, lakrass commented
nevermind: ill just fix the merge commit

2026-05-19 15:53 UTC, lakrass approved these changes

2026-05-19 15:53 UTC, merged

2026-05-27 00:37 UTC, macourteau commented
Apologies for the slow response on this, looks like I missed your comment back in November :-/ Thanks for merging!

2026-05-27 11:50 UTC, lakrass commented
No worries! :)